"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../../controllers/userController");
const auth_1 = require("../../utils/auth");
const userRouter = (0, express_1.Router)();
userRouter.route('/users').get(userController_1.getAllUsers);
userRouter.route('/').post(userController_1.createUser);
userRouter.route('/login').post(userController_1.loginUser);
userRouter.route('/user').get(auth_1.authMiddleware, userController_1.getSingleUser);
userRouter.route('/remove').delete(userController_1.deleteUser);
userRouter.route('/addSlices').post(auth_1.authMiddleware, userController_1.addSlices);
exports.default = userRouter;
