"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("../../controllers");
const auth_1 = require("../../utils/auth");
const userRouter = (0, express_1.Router)();
userRouter.route('/users').get(controllers_1.getAllUsers);
userRouter.route('/').post(controllers_1.createUser);
userRouter.route('/login').post(controllers_1.loginUser);
userRouter.route('/user').get(auth_1.authMiddleware, controllers_1.getSingleUser);
userRouter.route('/remove').delete(controllers_1.deleteUser);
exports.default = userRouter;
