"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteEntry = exports.createEntry = exports.getLastTwentyEntries = exports.getAllEntries = exports.deleteUser = exports.loginUser = exports.createUser = exports.getSingleUser = exports.getAllUsers = void 0;
const userController_1 = require("./userController");
Object.defineProperty(exports, "getAllUsers", { enumerable: true, get: function () { return userController_1.getAllUsers; } });
Object.defineProperty(exports, "getSingleUser", { enumerable: true, get: function () { return userController_1.getSingleUser; } });
Object.defineProperty(exports, "createUser", { enumerable: true, get: function () { return userController_1.createUser; } });
Object.defineProperty(exports, "loginUser", { enumerable: true, get: function () { return userController_1.loginUser; } });
Object.defineProperty(exports, "deleteUser", { enumerable: true, get: function () { return userController_1.deleteUser; } });
const SliceController_1 = require("./SliceController");
Object.defineProperty(exports, "getAllEntries", { enumerable: true, get: function () { return SliceController_1.getAllEntries; } });
Object.defineProperty(exports, "getLastTwentyEntries", { enumerable: true, get: function () { return SliceController_1.getLastTwentyEntries; } });
Object.defineProperty(exports, "createEntry", { enumerable: true, get: function () { return SliceController_1.createEntry; } });
Object.defineProperty(exports, "deleteEntry", { enumerable: true, get: function () { return SliceController_1.deleteEntry; } });
